### ISSUE TITLE
Initial to-do

### ISSUE THREAD

**Issue by aays** [ness-lab/recombinant-reads#1]
Gabe:
- [x] install anaconda on Linux computer (with Python 3!)
- [x] configure ssh on server using Ness Lab wiki article
- [x] clone repo locally

Ahmed:
- [x] look into installing htslib on the server and symlink into `bin`
- [x] create lookup table of tetrads to files
- [x] upload `all_break_points.txt` and `liu_sample_lookup.tsv` to repo

Gabe + Jimmy:
- technical stuff
    - [x] install FTP program (Transmit/FileZilla/etc)
- for the project
    - [x] write a script to iterate through to pull all reads in C2-1.1 between intervals denoted in `all_break_points.txt`
    - [x] get familiar with pysam's BAM writing functionality

**Comment by aays** [comment]
Updates after our meeting (28/1/2020) -

Broader task:
- [] create a new bam that spans the interval defined in the first line of `all_break_points.txt`, but only contains ~10% recombinant reads - i.e. with the remainder of the reads pulled from the same region, but from non-recombinant bams

Smaller to-dos:
- [] figure out how to write bam records after iterating through them with `fetch`

Note:
- when using an FTP program, need to use SFTP to connect to hpcnode1

**Comment by aays** [comment]
## 11/2/2020

Ahmed:
- [ ] sort out missing individuals in lookup table - C3-9.1 missing, SRR5243282 doesn't match up with expected individual
    - line 806 onwards in `all_break_points.txt` - these individuals are missing in the lookup table

Jimmy:
- [ ] get SNP counts for reads in bam files currently being subsampled from
- [ ] update bam fetching script with `cyvcf2` check that each read has at least 2 SNPs before being written

Jimmy:
- iterate through reads and count SNPs on each

**Comment by aays** [comment]
## 25/2/2020

Ahmed:

- [ ] adapt Jimmy's bam creation code into a script with `argparse`

Jimmy:

- [ ] get SNP counts in sliding windows of x kb (10 kb?) across a single chromosome

**Comment by aays** [comment]
## 10/3/2020

More mismatches in reads than expected - why is this? Checking query alignment values yields range from 8-31 (with one at 41)

Ahmed:
- [ ] talk to Rob about BAM quality score thresholds + do some lit scouring
- [ ] manually examine some of these mismatches and try to figure out what's going
- [ ] visually compare reads near start of given breakpoint in pysam vs IGV

Jimmy:

- [ ] find suspect reads and print out chunks of same region from read + reference - eyeball comparison - do we need to update the `SNP.start - query.reference_start` section? 
- [ ] play around with cigar string to see if we can more intelligently parse and readjust site positions if needed

**Comment by aays** [comment]
Ahmed:

- [ ] same as above - visually compare reads near start of given breakpoint in pysam vs IGV
- [ ] write up MWE for SeqIO reference querying

Jimmy:

- [ ] create (human) lookup table for these reads w/ information about whether they were called as recombinant/no match/etc

**Comment by aays** [comment]
Here's the MWE for looking at the reference sequence:

```python
from Bio import SeqIO
fname = 'chlamy.5.3.w_organelles.fasta' # filename may be different
for record in SeqIO.parse(fname, 'fasta'):
    if record.id == 'chromosome_1':
        chr1_rec = record
chr1_ref_seq = str(chr1_rec.seq)
```

**Comment by aays** [comment]
Ahmed:

- [ ] update Rob and read more about how to deal with misalignments/sequencing errors

Jimmy:

- [ ] create new table with just no-match reads
- [ ] check for bugs in code

**Comment by aays** [comment]
Ahmed: 

- [ ] convert notebook code base into scripts using `argparse` to remove hardcoding
- [ ] figure out how to work around insertions/deletions

Jimmy:
- [ ] create bam with just no-match reads
- [ ] try repeating mock bam creation process in a different crossover region
