### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by aays** [ness-lab/recombinant-reads#13]
Just a rough brain dump:

### Initial dev

- [ ] Complete phase change detection script by incorporating mate pairs (#6) 
- [ ] Add option to phase change detection script that will output metrics to a log
- [ ] Run above script on multiple mock bams (#7) and compile phase change read detection metrics

### Optimization

- [ ] Refactor to make code structure more class-based? 
- [ ] Reduce `pysam` dependence if possible, seeing as we just use the CIGAR strings, positions, and read ids (if need be) 
- [ ] Write unit tests for phase change detection
    - [ ] Set up continuous integration? 
- [ ] Look into speeding up with `pypy` and/or Cython

### Documentation

- [ ] Write function/class/method docstrings
- [ ] Package project for release (see [here](https://packaging.python.org/tutorials/packaging-projects/))
- [ ] Provide installation info
- [ ] Use `pylint` and [Google style guide](http://google.github.io/styleguide/pyguide.html#typing-imports) to clean code - style guide should be referred to during development where possible too

### Stretch goals

The key goal behind this specific project is to filter down bams for just reads with phase changes. However, if time allows, we can begin developing means of actually calling recombination events:

- [ ] Find way to to represent phase change information in compact way (#3) 
- [ ] Incorporate means of 'ignoring' ends of bams
- [ ] Draw schematic of all possible recombination event configurations (CO, CO-GC, NCO-GC)
- [ ] Develop means of using above schematic to incorporate both goals 1 and 2 above to call recombination event types
